// Code generated by "stringer -type=HeroType -trimprefix=Hero -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeroHunter-1]
	_ = x[HeroDarwf-2]
	_ = x[HeroKnight-3]
}

const _HeroType_name = "HuntersmallKnight"

var _HeroType_index = [...]uint8{0, 6, 11, 17}

func (i HeroType) String() string {
	i -= 1
	if i < 0 || i >= HeroType(len(_HeroType_index)-1) {
		return "HeroType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _HeroType_name[_HeroType_index[i]:_HeroType_index[i+1]]
}
